compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
downcast_bf16: 'yes'
machine_rank: 0
main_training_function: main
mixed_precision: bf16
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
num_machines: 1
num_processes: 8